### ISSUE TITLE
Maybe there is a little problem in the code file woa_svm.py

### ISSUE THREAD

**Issue by M-Kylie** [Xrondev/HKU-comp7404#2]
In the function "whale_optimization_algorithm",  the loop code (in the while loop):
                if np.linalg.norm(A) < 1:
                    # update the position by Eq.1
                    population[idx] = best_whale - A * (C * best_whale - whale)   
According to the paper,  why it is not  : population[idx] = whale - A * (C * best_whale - whale).

And in the da_svm.py, where does the levy_flight come from? Because I can't find any description in the paper you introduced. 

Thank you for reading my comment, and I am hoping to receive your response.

**Comment by Xrondev** [comment]
For that implementation problem, you may refer to the original paper of WOA [The whale optimization algorithm](https://www.sciencedirect.com/science/article/abs/pii/S0965997816300163?via%3Dihub) and the pyMetaheauristic repo I mentioned in your last issue. I don't know if the implementation is wrong or not now, but if the problem does exist, you can highlight the formula for me and create a pull request if you want to fix it.
And for your second problem, actually, we also did not find the levy_flight function in the paper, and the formula seems to not even appear in the original paper that proposed the DA(I am not quite sure; check it, please). It seems like in the end we referred to the pyMetaHeauristic for the levy function.
Anyway, you can try to find more papers or repos and keep searching for those terms or formulas. The paper we implemented has many uncertain parts and errors(e.g., figure 4 is for DA, but whales in the steps description), so you might have to look for a broader range of resources to study instead of sticking to only this paper.

**Comment by M-Kylie** [comment]
<img width="355" alt="formula" src="https://github.com/Xrondev/HKU-comp7404/assets/80374879/4d49d045-fbd6-45ac-853b-fc65657d909a">
This is the formula in the paper(Eq.1), I took a screenshot of it, you can refer to it. I'm not very familiar with using Github, so I can only rely on you to make code changes if you need. Thank you for your suggestions, I will refer to other papers and the repository you mentioned.

**Comment by Xrondev** [comment]
> <img alt="formula" width="355" src="https://private-user-images.githubusercontent.com/80374879/315263551-4d49d045-fbd6-45ac-853b-fc65657d909a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjA3MTUsIm5iZiI6MTcxMTAyMDQxNSwicGF0aCI6Ii84MDM3NDg3OS8zMTUyNjM1NTEtNGQ0OWQwNDUtZmJkNi00NWFjLTg1M2ItZmM2NTY1N2Q5MDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDExMjY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMjk0YTliZDY0NTJjMjI1ZDA1ZDAwOGUxMGVhNTQzOGZkZjA0YjI2OGNmODM1YTY0ZTExZjEyZDU5YTExMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KeFZIEZ-E51tTsxtBkEfwPQSiy97xWmTXDOpkATb7is"> This is the formula in the paper(Eq.1), I took a screenshot of it, you can refer to it. I'm not very familiar with using Github, so I can only rely on you to make code changes if you need. Thank you for your suggestions, I will refer to other papers and the repository you mentioned.

According to the original paper and the pyMetahuristic I mentioned, the formula should be 
![image](https://github.com/Xrondev/HKU-comp7404/assets/61485096/db6f57c1-c949-47dd-9dc8-084284f143e2)
where the X star denotes the best whale position. (pp.53)

Another code example from pyMetaheuristic is [Here](https://github.com/Valdecy/pyMetaheuristic/blob/main/pyMetaheuristic/algorithm/woa.py) at L45 and L70. Please note that the if condition is different from our implementation, but the formula uses the best whale idx.

Therefore, this might be another error that appeared in the paper... Please refer to other resources if you do believe the implementation needs to be corrected, thanks.

**Comment by M-Kylie** [comment]
Oh, I see...So the paper I referenced is incorrect. Could you tell me the formula you screenshot above is from which paper?

**Comment by Xrondev** [comment]
> Oh, I see...So the paper I referenced is incorrect. Could you tell me the formula you screenshot above is from which paper?

Sure, the paper is mentioned in my first reply. Please refer to this paper, which proposed the WOA: 
[The whale optimization algorithm](https://www.sciencedirect.com/science/article/abs/pii/S0965997816300163?via%3Dihub)

> For that implementation problem, you may refer to the original paper of WOA [The whale optimization algorithm](https://www.sciencedirect.com/science/article/abs/pii/S0965997816300163?via%3Dihub) and the pyMetaheauristic repo I mentioned in your last issue. I don't know if the implementation is wrong or not now, but if the problem does exist, you can highlight the formula for me and create a pull request if you want to fix it. And for your second problem, actually, we also did not find the levy_flight function in the paper, and the formula seems to not even appear in the original paper that proposed the DA(I am not quite sure; check it, please). It seems like in the end we referred to the pyMetaHeauristic for the levy function. Anyway, you can try to find more papers or repos and keep searching for those terms or formulas. The paper we implemented has many uncertain parts and errors(e.g., figure 4 is for DA, but whales in the steps description), so you might have to look for a broader range of resources to study instead of sticking to only this paper.

**Comment by M-Kylie** [comment]
Thanks!!You are my hero!

**Comment by Xrondev** [comment]
The issue has been closed since no more comments were received.
